project:
  type: website

website:
  title: "Lin517: Natural Language Processing"
  sidebar:
    collapse-level: 3
    contents:
      - section: "Resources"
        contents:
          - href: "resources/reading/index.qmd"
            text: "Reading a technical paper"
          - href: "resources/notation/index.qmd"
            text: "Mathematical notation"
      - section: "Lecture Notes"
        contents: 
          - section: "Intro"
            contents:
              - href: "lectures/what_is_nlp/index.qmd"
                text: "What is NLP?"
          - section: "Data Sparsity and Processing"
            contents:
              - href: "lectures/data_sparsity/data_sparsity.qmd"
                text: "Data Sparsity"
              - href: "lectures/data_processing/index.qmd"
                text: "Data processing"
              - href: "lectures/data_processing/addendum.qmd"
                text: "Data processing -- addendum"
              - href: "lectures/lem_stem/index.qmd"
                text: "Lemmatizing and stemming"
          - section: "ngrams"
            contents:
              - href: "lectures/ngram/index.qmd"
              - href: "lectures/ngram/01-ngram-eval.qmd"
              - href: "lectures/ngram/02_smoothing.qmd"
          - section: "Word Vectors"
            href: "lectures/word_vectors/index.qmd"
            contents:
              - href: "lectures/word_vectors/01_concept.qmd"
              - href: "lectures/word_vectors/02_vectors_examples.qmd"
              - href: "lectures/word_vectors/03_word2vec.qmd"
          - section: "Neural Networks"
            contents:
              - href: "lectures/gradient_descent/01_gradient_descent.qmd"
              - href: "lectures/matrix_multiplication/index.qmd"
              - href: "lectures/neural_networks/index.qmd"
              - href: "lectures/neural_networks/word_embeddings.qmd"
          - section: "Models"
            contents:
              - href: "lectures/evaluation/index.qmd"
      - section: "python sessions"
        contents:
          - href: "python_sessions/00_session1.qmd"
          - href: "python_sessions/01_session2.qmd"
          - href: "python_sessions/02_session3.qmd"
          - href: "python_sessions/03_session4.qmd"
          - href: "python_sessions/04_session5.qmd"
  page-navigation: true
  
format:
  html:
    theme: materia
    css: styles.css
    toc: true
    fig-cap-location: margin
    include-in-header: googlefont.html
    mainfont: "'Atkinson Hyperlegible', sans-serif"
    smooth-scroll: true
knitr: 
  opts_chunk: 
    message: false

editor: visual

output-format: html

execute:
  freeze: auto
