project:
  type: website

website:
  title: "Lin517: Natural Language Processing"
  sidebar:
    contents:
      - section: "Resources"
        contents:
          - href: "reading/index.qmd"
            text: "Reading a technical paper"
          - href: "notation/index.qmd"
            text: "Mathematical notation"
      - section: "Lecture Notes"
        contents: 
          - href: "what_is_nlp/index.qmd"
            text: "What is NLP?"
          - href: "data_sparsity/data_sparsity.qmd"
            text: "Data Sparsity"
format:
  html:
    theme: materia
    css: styles.css
    toc: true
    fig-cap-location: margin
    include-in-header: googlefont.html
    mainfont: "'Atkinson Hyperlegible', sans-serif"

editor: visual

execute:
  freeze: auto
