project:
  type: website

website:
  title: "Lin517: Natural Language Processing"
  sidebar:
    collapse-level: 1
    contents:
      - section: "Resources"
        contents:
          - href: "resources/reading/index.qmd"
            text: "Reading a technical paper"
          - href: "resources/notation/index.qmd"
            text: "Mathematical notation"
      - section: "Lecture Notes"
        contents: 
          - href: "lectures/what_is_nlp/index.qmd"
            text: "What is NLP?"
          - href: "lectures/data_sparsity/data_sparsity.qmd"
            text: "Data Sparsity"
          - href: "lectures/data_processing/index.qmd"
            text: "Data processing"
      - section: "python sessions"
        contents:
          - href: "python_sessions/00_session1.qmd"
            text: "Session 1"
  page-navigation: true
  
format:
  html:
    theme: materia
    css: styles.css
    toc: true
    fig-cap-location: margin
    include-in-header: googlefont.html
    mainfont: "'Atkinson Hyperlegible', sans-serif"

editor: visual

output-format: all

execute:
  freeze: auto
