{
  "hash": "2ef7d0ad44f095ae573bfca409e9fde7",
  "result": {
    "markdown": "---\ntitle: \"Mathematical Notation\"\neditor: visual\nformat:\n  html: default\n  pdf:\n    output-file: \"notation\"\nauthor: \"Josef Fruehwald\"\nlicense: \"CC BY-SA 4.0\"\ndate: \"2022-8-20\"\n---\n\n\n\n# Variables\n\nThe most common variables we're going to be seeing:\n\n-   $x, y$\n\n    -   Stand-ins for numbers, usually a list, or vector, of numbers\n\n    -   $y$ is often some kind of \"outcome\" variable\n\n    -   $x$ is often some kind of input, or predictor variables\n\n    -   e.g. \"We want to predict how many ice cream cones, $y$, we'll sell if it's a specific temperature, $x$.\n\n-   $X, Y$\n\n    -   Stand ins for categorical variables\n\n-   $w$\n\n    -   A special variable for a word\n\n-   $c$\n\n    -   A \"count\" of something\n\n-   $p$\n\n    -   A probability\n\n-   $N$\n\n    -   Usually, the total number of something\n\n-   $n$\n\n    -   A contextual number. E.g. \"In $n+1$ days (that is, tomorrow)...\"\n\n-   $n,m$\n\n    -   When $n$ and $m$ are used together, it's often to describe the number of rows and columns of a matrix.\n\n-   $A, B$\n\n    -   These are almost always used for matrices\n\n    -   Capital roman letters are often a clue we're looking at a matrix (but not always)\n\n-   $\\lambda$\n\n    -   \"lambda\"\n\n    -   Often used for an arbitrary value you multiply things by.\n\n-   $k$\n\n    -   Often used for an arbitrary value you add things to.\n\n-   $\\delta$\n\n    -   \"delta\"\n\n    -   Often used to describe a **d**ifference of some kind\n\n-   $\\alpha, \\beta, \\gamma$\n\n    -   \"alpha\", \"beta\", \"gamma\"\n\n    -   Used for model parameters\n\n-   $\\theta$\n\n    -   \"theta\"\n\n    -   Also used as a model parameter.\n\n    -   Or, to describe an angle (in radians)\n\n## \"Decorated\" variables\n\n-   $\\hat{y}$\n\n    -   \"y hat\"\n\n    -   A predicted value for $y$\n\n    -   e.g. \"I predicted $\\hat{y}$ ice cream cones to be sold, but they actually sold $y$.\n\n-   $\\bar{y}$\n\n    -   \"y bar\"\n\n    -   The average value of $y$\n\n-   $y^*$\n\n    -   \"y star\"\n\n    -   A modified value of $y$\n\n# Indices\n\n## One Dimensional\n\nWhen we have a variable that contains a list of values, each individual value will be described with an \"index\". For example, if we had a variable $X$ that contained the names of the week.\n\n$$\nX = (\\text{Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday})\n$$\n\nThen the *first* value in the list would be $X_1$, and we could say $X_1 = \\text{Monday}$. You'd usually pronounce $X_1$ as \"X sub 1\".\n\nSometimes we want to be able to refer to a generic value in the list $X$ and for that we'd use an index variable like $X_i$ (pronounced \"X sub i\"). The most common letters used to indicate generic indices are $i, j, k$.\n\nWe can do math on the indices also. So, if the name of today is $X_i$, then the name of tomorrow is $X_{i+1}$. The name of yesterday is $X_{i-1}$. The day after tomorrow would be $X_{i+2}$.\n\nWe can also include a range of numbers in the indices. So, the names of the first three days of the week are $X_{1:3} = (\\text{Monday, Tuesday, Wednesday})$. The names of yesterday, today, and tomorrow are $X_{i-1:i+1}$.\n\n## Two Dimensional\n\nWe could imagine a Month as being a matrix $M$ made up of 4 weeks, with each week being 7 days.\n\n$$\nM = \\left[ \\begin{array}{lllllll}\n\\text{Monday} & \\text{Tuesday} & \\text{Wednesday} & \\text{Thursday} &  \\text{Friday} &     \\text{Saturday} & \\text{Sunday} \\\\ \n\\text{Monday} & & & \\dots & & & \\text{Sunday}\\\\\n\\vdots & & & \\ddots\\\\\n\\text{Monday} & & & \\dots & & &\\text{Sunday}\\\\\n \\end{array} \\right]\n$$\n\nIf we wanted to get the name of the third day during the first week, it would be $M_{1, 3} = \\text{Wednesday}$. When giving numeric indices of a matrix, the rows (the parts going across) come first, and the columns (the parts going up and down) come second. So, we'd describe the matrix $M$ as being a $4\\times7$ \"four by seven\" matrix.\n\nTo refer to a day of the month generically, we'd use $M_{i,j}$ (pronounced \"M sub i, j\"). We can also use ranges in these indices. So, to refer to the second week of the month, we'd use $M_{2,1:7}$. Or, to refer to all of the Saturdays in the month, we'd use $M_{1:4,6}$.\n\nAnd, we can also use math in these indices. So, we could refer to \"a week from today\" with $M_{i+1,j}$.\n\n## Matrix Transposition\n\nThe one special notation related to matrices is \"transposition\", which basically takes a matrix and flips it.\n\n$$\nA = \\left[\\begin{array}{ccc}\n1 & 2 & 3 \\\\\n4 & 5 & 6\n\\end{array}\n\\right]\n$$\n\n$$\nA^\\intercal = \\left[\\begin{array}{cc}1 & 4\\\\\n2 & 5 \\\\\n3 & 6 \\end{array}\\right]\n$$\n\nThe little $^\\intercal$ indicates that we're transposing the matrix. You'd pronounce $A^\\intercal$ as \"A transpose\".\n\nThe transpose operation can apply to single lists too. This will eventually be important.\n\n$$\nx = [1, 2, 3, 4]\n$$\n\n$$\nx^\\intercal = \\left[\\begin{array}{c} 1\\\\2\\\\3\\\\4 \\end{array}\\right]\n$$\n\nAgain, $x^\\intercal$ is pronounced \"x transpose.\"\n\n# Functions\n\n## Generic\n\n-   $f(), g()$\n\n    -   These are the most common \"functions\" you'll see. Usually in a whole formula like $y = f(x)$ (pronounced \"y equals f of x\").\n\n    -   It means \"we stick the value $x$ in and $y$ comes out.\n\n    -   *What* $f()$ or $g()$ (or whatever name we give the function) is needs to be defined. They don't have a fixed meaning.\n\n## Specialized\n\n-   $P()$\n\n    -   The function $P()$ refers to the probability of whatever we put in.\n\n    -   $P(X_i)$ returns the probability of a specific $X_i$ value.\n\n    -   We'd refer to the specific value the $P()$ returns with the variable $p$, usually with the same index. So $p_i = P(X_i)$.\n\n-   $C()$\n\n    -   The function $C()$ returns the count of whatever we put in.\n\n    -   In the matrix above, $C(\\text{Monday}) = 4$\n\n    -   We'd refer to the specific count value of something with the variable $c$, usually with the same index. So $c_{i} = C(X_i)$.\n\n# Summation and Product\n\n## Summation\n\n$\\sum$\n\nThis operator indicates that we are adding together numbers in a list. Let's look at the table of the height of actors, in cm who played Spider-Man in *Spider-Man: No Way Home*.\n\n\n\n::: {.cell-output-display}\n|Actor           | Height (cm)|\n|:---------------|-----------:|\n|Tobey Maguire   |         172|\n|Andrew Garfield |         179|\n|Tom Holland     |         169|\n:::\n\n\n\nWe would say that there are $N=3$ actors who played Spider-Man in the movie. And we could represent their heights in a variable $y$, and say\n\n$$\ny = (172, 179, 169)\n$$\n\nThe height of the first actor would be $y_1$, which equals $172$, and the way to refer to any given height on the list would be $y_i$.\n\nTo get the total height of the actors (like if one stood on the head of the other), we would have to sum it up, which we could represent like this:\n\n$$\nh = y_1 + y_2 + y_3\n$$\n\nOr, we could use summation notation\n\n$$\nh = \\sum_{i=1}^Ny_i\n$$\n\nThe way to read this out loud is \"h equals the sum of y sub i from i equals 1 to N\". The $i=1$ part underneath the $\\sum$ means \"start getting values out of $y$ starting with 1\". The $N$ at the top means \"keep adding 1 to $i$ until $i = N$.\"\n\nWhat the whole notation is going to do is pull out every value of $y$ and add them together.\n\nIf you know how to do some coding, sometimes it's easier to understand the mathematical notation to see it in code.\n\n\n\n\n\n::: {.cell}\n\n````{.cell-code}\n```{{python}}\ny = [172, 179, 169]\nN = 3 # = len(y)\nh = 0 \n\nfor i in range(N):\n  h = h + y[i]\n\nprint(h)\n```\n````\n\n::: {.cell-output .cell-output-stdout}\n```\n520\n```\n:::\n:::\n\n\n\n## Product\n\n$\\prod$\n\nThe product operator, $\\prod$, works a lot like the the summation operator, except instead of adding numbers together, it multiplies them. For example, let's say we're keeping track of the day-to-day changes in the number of visitors to a website.\n\n| Day | Percent Change | Multiplier |\n|-----|----------------|------------|\n| 1   | up 1%          | 1.01       |\n| 2   | no change      | 1.00       |\n| 3   | down 5%        | 0.95       |\n\nWe can get the total proportional change over these three days by multiplying the proportions together. Writing it out the long way, it's\n\n$$\nN = 3\n$$\n\n$$\ny = (1.01, 1, 0.95)\\\\\n$$\n\n$$\nt = y_1\\cdot y_2\\cdot y_3\n$$\n\nIn product notation, though, it looks like this.\n\n$$\nt = \\prod_{i=1}^Ny_i\n$$\n\nAgain, if you're more comfortable with programming code, it's equivalent to this.\n\n\n\n::: {.cell}\n\n````{.cell-code}\n```{{python}}\ny = [1.01, 1, 0.95]\nN = 3\nt = 1\n\nfor i in range(N):\n  t = t * y[i]\n\nprint(f\"{t:.4}\")\n```\n````\n\n::: {.cell-output .cell-output-stdout}\n```\n0.9595\n```\n:::\n:::\n\n\n\n# Probability\n\nThere's not space in this tutorial for an *entire* intro to probability theort, so here I'll just provide enough context to describe how we notate key concepts.\n\n## Conditional Probability\n\nThe \"conditional probability\" is the probability of some value or event $Y$, holding constant some other value or event $X$ . For example, maybe\n\n$$\nY = \\text{I am teaching}\n$$\n\nand\n\n$$\nX_1 = \\text{It is a Monday}\n$$\n\nand\n\n$$\nX_6=\\text{It is a Saturday}\n$$\n\nThe probability that I am teaching a class is is a lot lower on a Saturday than on a Monday. We can express these like so.\n\n$$\np_1 = P(Y | X_1)\n$$\n\na.k.a \"p sub 1 equals the probability I am teaching, given that it is a Monday\".\n\n$$\np_6 = P(Y|X_6)\n$$\n\na.k.a. \"p sub 6 equals the probability I am teaching given that it is a Saturday\"\n\nand\n\n$$\np_6 < p_1\n$$\n\nThe key piece of notation in the expressions above is the $|$ (the \"pipe\") inside of the $P()$ function.\n\n## Joint Probability\n\nThe joint probability is the probability of two values or events happening together. It's **not** the same as a conditional probability of one event given the other, but explaining why requires more time and space.\n\nIf we stick with the same events as above (\"I am teaching\" and \"It is a Monday\") the joint probability of \"I am teaching *and* it is a Monday\" would be notated as\n\n$$\nq_1 = P(Y,X_1)\n$$\n\nThe comma inside the $P()$ function means \"and.\"\n\n------------------------------------------------------------------------\n\n-   [pdf](notation.pdf)\n\n[![CC BY-SA 4.0](assets/license.png)](http://creativecommons.org/licenses/by-sa/4.0/)\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}